export { default as Login } from 'views/LoginPage/Login';
export { default as Signup } from 'views/SignupPage/Signup';
export { default as NotFound} from 'views/NotFoundPage/NotFound';
export { default as LandingPage } from 'views/LandingPage/LandingPage';
export { default as Listings } from 'views/ListingsPage/Listings';
export { default as ContactPage } from 'views/ContactPage/Contact';
export { default as ServiceProviders } from 'views/ServiceProvidersPage/ServiceProviders';
export { default as UserPage } from 'views/UserPage/UserPage';
export { default as SearchPage } from 'views/SearchPage/SearchPage';
export { default as ProfilePage } from 'views/ProfilePage/ProfilePage';
export { default as ConfirmCompanyUser } from 'views/ConfirmCompanyUser/ConfirmCompanyUser';
